version: '2.1'
services:

  iota-node:
    build:
      context: .
      dockerfile: Dockerfile
    image:
      bluedigits/iota-node:latest
    ports:
      - ${API_PORT:-14265}
      - ${UDP_PORT:-14600}
      - ${TCP_PORT:-15600}
    volumes:
      - ./iri/data:/iri/data
      - ./iri/conf:/iri/conf
    environment:
      - API_PORT=${API_PORT:-14265}
      - UDP_PORT=${UDP_PORT:-14600}
      - TCP_PORT=${TCP_PORT:-15600}
    command: ./docker-entrypoint.sh
